### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by GregoryPye**

### CODE REVIEW

**Comment by GregoryPye** [comment]
Chnaged title (also changed title of my fork)

**Comment by 006fix** [comment]
string_storage0 = ""
string_storage1t9 = ""


file_num_holder = -1
for file in dirs:
    file_num_holder += 1
    for item in range(len(final_digit_storage[file_num_holder])):
        if item%1000 == 0:

print(str(round(100*(item/len(final_digit_storage[file_num_holder]))),3) +
"% complete")
        if final_digit_storage[file_num_holder][item] == "0":
            string_storage0 += json_storage[file][item]['review_detail']
        else:
            string_storage1t9 += json_storage[file][item]['review_detail']

text_filename0 = filename = sourcepath + r"\\" + "test0.txt"
text_filename1t9 = filename = sourcepath + r"\\" + "test1t9.txt"

f1 = open(text_filename0, "w+")
f1.write(string_storage0)
f1.close()

f2 = open(text_filename1t9, "w+")
f2.write(string_storage1t9, "w+")
f2.close()

**Comment by 006fix** [comment]
sourcepath2 = r"C:\Users\Alan\Desktop\Text_Output"
string_storage0 = ""
string_storage1t9 = ""


file_num_holder = -1
for file in dirs:
    file_num_holder += 1
    for item in range(len(final_digit_storage[file_num_holder])):
        if item%1000 == 0:

print(str(round(100*(item/len(final_digit_storage[file_num_holder])), 3)) +
"% complete")
        if final_digit_storage[file_num_holder][item] == "0":
            string_storage0 += json_storage[file][item]['review_detail']
        else:
            string_storage1t9 += json_storage[file][item]['review_detail']

text_filename0 = filename = sourcepath2 + r"\\" + "test0.txt"
text_filename1t9 = filename = sourcepath2 + r"\\" + "test1t9.txt"

f1 = open(text_filename0, "w+")
f1.write(string_storage0)
f1.close()

f2 = open(text_filename1t9, "w+")
f2.write(string_storage1t9, "w+")
f2.close()

**Comment by GregoryPye** [comment]
Not quite working but heading to bed.  THought I'd ping the version I was
playing with.  Couple of notes :-

   - All the processing is inline so this can handle a stream, not need to
   do it all in one go.
   - Tested the review_year column add - seems to work.
   - Aiming to use a compiled RegEx to do the date finding and replacing
   ... not got to test that yet but you can see the code below.  Same model
   could be used for film title I suspect


# Define the regex to use for year matching
# Base on starting with 19 or 20, then two digits
# regex compiled as it wil lbe used many times over
year_pattern_regex = re.compile(r"(19|20)\d{2}")
#

startTime = time.time()
for current_file in files_to_load:
    print(f"Starting load of {current_file}...")
    file_to_read = data_folder / current_file
    with open(file_to_read, mode='r') as file:
        new_reviews = json.load(file)
        for review in new_reviews:
            # Add a column with the year
            review['review_year'] = review['review_date'][-4:]


# Replace any occurrances of a year in the 'review_detail' with QQQQ
            year_pattern_regex.sub('QQQQ',review['review_detail'])

            reviews_json.append(review)
    print(f"Finished load of {current_file} at {time.time() - startTime:.2f}
 total seconds elapsed")
print(f"Loading complete after {time.time() - startTime:.2f} seconds, {len(
reviews_json):,} items in reviews_json")

**Comment by 006fix** [comment]
I'll do 2 seperate comments, 1 r.e above 1 r.e code to get strings into text format files

r.e the above - you are correct you could use a regex substitution. I cant quite remember how regex works, but I assume it could find, say "x2020x" and replace it with "xQQQQx"?

I think it depends on how much you wanted to remove. Your method would remove any instance of the remove date, but it would also remove, say, "1940's" (in reference to the film period), or "200000" (in whatever context). So it's a little bit more agressive than mine is.

Can't see the header part of your code obviously, but I believe for regex you need to use a library to get it to work, which may be an issue?

I'm also very unsure the syntax you're using - it looks pandas syntax, but afaik jsons arrive in a dictionary format? If so that'll mean our code isn't easy to use for each other without settling on one. On the final segment of code, I can't quite see how it actually does the replacement?

**Comment by 006fix** [comment]
comment r.e getting string lists for code:

see below. This is only designed to operate on one single json file at a time, which should be changed - once all are written to seperate files they can be shuffled to the same file and will work fine. If required, its setup so that the correct json file will be added to the name of the file for future reference. They're also numbered sequentially, contain 1000 records each (or less in the instance of the final file), contain a distinct seperator string which can be removed later ("gotolocfind" + str(number)) where number = instance of row in json file. We could remove that later too

This runs very quickly - exports all 1010 files in about 5 minutes.

It will also allow for stopping midway and restarting (although it runs so fast this turns out to be irrelevant)

sourcepath2 = r"C:\Users\Alan\Desktop\Text_Output"
string_storage = ""



file_num_holder = -1
iterations_completed = -1
dirs2 = os.listdir(sourcepath2)
files_found = 0
max_val = 0

for file in dirs2:
    files_found += 1
    
    
    
output_loc_list = []    
if files_found > 0:
    for file in dirs2:
        detloc_start = file.index("[")
        detloc_end = file.index("]")
        outputval = int(file[detloc_start+1:detloc_end])
        output_loc_list.append(outputval)
        print(outputval)
        
if files_found > 0:
    output_loc_list.sort(reverse=True)
    max_val = output_loc_list[0]
    
counter = 0
complete_count = 0

for file in dirs:
    for string2 in range((1000*max_val), len(json_storage[file])):
        counter+=1
        if counter < 1000:
            string_storage += json_storage[file][string2]['review_detail']
            string_storage += " "
            string_storage += "gotolocfind" + str(string2)
            string_storage += " "
        else:
            string_storage += json_storage[file][string2]['review_detail']
            string_storage += " "
            string_storage += "gotolocfind" + str(string2)
            string_storage += " "
            text_filename = sourcepath2 + r"\\" + "(" + str(file) + ")_" + "test[" + str(int(((string2+1)/1000))) + "].txt"
            string_storage.encode("ascii",errors="ignore")
            f1 = open(text_filename, "w+", encoding="utf-8")
            print(counter)
            print(string2)
            f1.write(string_storage)
            f1.close()
            string_storage = ""
            counter = 0
            complete_count += 1
            print("There have been " + str(complete_count) + " files created.")

            
print("This step has finished!")

**Comment by 006fix** [comment]
realised the code needed a slight tweak to handle the final N cases, where N = len(records)%1000

added that, and uploaded the new full version to the main initial commit

**Comment by GregoryPye** [comment]
> I'll do 2 seperate comments, 1 r.e above 1 r.e code to get strings into text format files

My pre-process trial is in a different file, so you can pull that into the repo and it won't clash with yours.

> 
> r.e the above - you are correct you could use a regex substitution. I cant quite remember how regex works, but I assume it could find, say "x2020x" and replace it with "xQQQQx"?

Correct

> 
> I think it depends on how much you wanted to remove. Your method would remove any instance of the remove date, but it would also remove, say, "1940's" (in reference to the film period), or "200000" (in whatever context). So it's a little bit more agressive than mine is.

True, though I can amend to match only a space, a date, and then a non-text character.  I could extract just the year in question/ one before  (sliced from the review date) ... but the way I have it right now allows use of a compiled regex, so it needs to remain constant for every entry.  Suggest that for now e simply pull out all year refs and see how it goes; we can always change later

> 
> Can't see the header part of your code obviously, but I believe for regex you need to use a library to get it to work, which may be an issue?

Its 're' and I did include it - you'll see it when I load the file to my repo and do a pull request.

> 
> I'm also very unsure the syntax you're using - it looks pandas syntax, but afaik jsons arrive in a dictionary format? If so that'll mean our code isn't easy to use for each other without settling on one. On the final segment of code, I can't quite see how it actually does the replacement?

I'll add some comments.  Not really using panda (and not even super clued up on it!).  My thinking was to that we read in JSON formatted file and spit out a JSON formatted file.  What we then do later is a different matter

**Comment by GregoryPye** [comment]
Pulled your change into my repo so you should be able to just accept this whole request - it doesn;t change your file

**Pull request merged**
